export enum RoutePaths {
  Login = "/login",
  Register = "/register",
  Home = "/",
  Aboutus = "/Aboutus",
  Faq = "/faq",
  ContactUs = "/contactus",
  Userprofile = "/Userprofile",
  SeeRequest = "seeRequest",
  Requests = "requests",
  Posthelp = "posthelp",
  ElderRequest = "elderrequest",
  VolunteerRequest = "volunteerrequest",
  Review = "/review",
  RatingStar = "/addreviewpage",
  Chat = "/Chat",
  Inheritance = "/credittransfer",
  Blog = "/blog",
  AddBLog = "/addblogs"
}
